version: '3'
services:
  node_app:
    container_name: node-container
    build: 
      context: .
    volumes:
      - .:/app
      - /app/node_modules # This line is likely causing the issue
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: learnify
    volumes:
      - postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_db:
